// Code generated by ___go_build_github_com_dminGod_sepaToGo. DO NOT EDIT.

package iso20022_auth_022_001_02

import (
	"bytes"
	"encoding/base64"
	"encoding/xml"
	"time"
)

type AccountIdentification4Choice struct {
	IBAN IBAN2007Identifier            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IBAN"`
	Othr GenericAccountIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Othr"`
}

type AccountSchemeName1Choice struct {
	Cd    ExternalAccountIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type ActiveCurrencyAndAmount struct {
	Value float64            `xml:",chardata"`
	Ccy   ActiveCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveCurrencyCode string

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

// May be one of ADDR, PBOX, HOME, BIZZ, MLTO, DLVY
type AddressType2Code string

type AddressType3Choice struct {
	Cd    AddressType2Code        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry GenericIdentification30 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type BICFIDec2014Identifier string

// May be one of WIBO, TREA, TIBO, TLBO, SWAP, STBO, PRBO, PFAN, NIBO, MAAA, MOSP, LIBO, LIBI, JIBA, ISDA, GCFR, FUSW, EUCH, EUUS, EURI, EONS, EONA, CIBO, CDOR, BUBO, BBSW
type BenchmarkCurveName2Code string

type BenchmarkCurveName4Choice struct {
	ISIN ISINOct2015Identifier   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ISIN"`
	Indx BenchmarkCurveName2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Indx"`
	Nm   Max25Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Nm"`
}

type BinaryFile1 struct {
	MIMETp         Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MIMETp,omitempty"`
	NcodgTp        Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 NcodgTp,omitempty"`
	CharSet        Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CharSet,omitempty"`
	InclBinryObjct Max100KBinary `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 InclBinryObjct,omitempty"`
}

type BranchAndFinancialInstitutionIdentification6 struct {
	FinInstnId FinancialInstitutionIdentification18 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 FinInstnId"`
	BrnchId    BranchData3                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 BrnchId,omitempty"`
}

type BranchData3 struct {
	Id      Max35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id,omitempty"`
	LEI     LEIIdentifier   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LEI,omitempty"`
	Nm      Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Nm,omitempty"`
	PstlAdr PostalAddress24 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PstlAdr,omitempty"`
}

type CashAccount38 struct {
	Id   AccountIdentification4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	Tp   CashAccountType2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Tp,omitempty"`
	Ccy  ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ccy,omitempty"`
	Nm   Max70Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Nm,omitempty"`
	Prxy ProxyAccountIdentification1  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prxy,omitempty"`
}

type CashAccountType2Choice struct {
	Cd    ExternalCashAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type CashCollateral5 struct {
	CollId    Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CollId,omitempty"`
	CshAcctId AccountIdentification4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CshAcctId,omitempty"`
	AsstNb    Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AsstNb,omitempty"`
	DpstAmt   ActiveCurrencyAndAmount      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DpstAmt,omitempty"`
	DpstTp    DepositType1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DpstTp,omitempty"`
	MtrtyDt   ISODate                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MtrtyDt,omitempty"`
	ValDt     ISODate                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ValDt,omitempty"`
	XchgRate  float64                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XchgRate,omitempty"`
	CollVal   ActiveCurrencyAndAmount      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CollVal"`
	Hrcut     float64                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Hrcut,omitempty"`
}

type CertificateIdentification1 struct {
	MsgId       Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MsgId,omitempty"`
	AcctSvcrRef Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AcctSvcrRef,omitempty"`
	PmtInfId    Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PmtInfId,omitempty"`
	InstrId     Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 InstrId,omitempty"`
	EndToEndId  Max35Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 EndToEndId,omitempty"`
	Prtry       ProprietaryReference1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry,omitempty"`
}

type CertificateReference1 struct {
	Id CertificateIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	Dt ISODate                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Dt"`
}

type ClearingSystemIdentification2Choice struct {
	Cd    ExternalClearingSystemIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type ClearingSystemMemberIdentification2 struct {
	ClrSysId ClearingSystemIdentification2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ClrSysId,omitempty"`
	MmbId    Max35Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MmbId"`
}

// May be one of EMAL, FAXI, FILE, ONLI, PHON, POST, PROP, SWMT, SWMX
type CommunicationMethod4Code string

type Contact4 struct {
	NmPrfx    NamePrefix2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 NmPrfx,omitempty"`
	Nm        Max140Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Nm,omitempty"`
	PhneNb    PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PhneNb,omitempty"`
	MobNb     PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MobNb,omitempty"`
	FaxNb     PhoneNumber                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 FaxNb,omitempty"`
	EmailAdr  Max2048Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 EmailAdr,omitempty"`
	EmailPurp Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 EmailPurp,omitempty"`
	JobTitl   Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 JobTitl,omitempty"`
	Rspnsblty Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Rspnsblty,omitempty"`
	Dept      Max70Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Dept,omitempty"`
	Othr      []OtherContact1             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Othr,omitempty"`
	PrefrdMtd PreferredContactMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PrefrdMtd,omitempty"`
}

type ContractBalance1 struct {
	Tp        ContractBalanceType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Tp"`
	Amt       ActiveCurrencyAndAmount    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt"`
	CdtDbtInd CreditDebit3Code           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CdtDbtInd"`
}

type ContractBalanceType1Choice struct {
	Cd    ExternalContractBalanceType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type ContractClosureReason1Choice struct {
	Cd    ExternalContractClosureReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type ContractCollateral1 struct {
	TtlAmt   ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TtlAmt"`
	CollDesc []CashCollateral5       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CollDesc,omitempty"`
	AddtlInf Max1025Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AddtlInf,omitempty"`
}

type ContractRegistrationReference1Choice struct {
	RegdCtrctId Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegdCtrctId"`
	Ctrct       DocumentIdentification28 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ctrct"`
}

type ContractRegistrationStatement2 struct {
	StmtId             Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 StmtId,omitempty"`
	RptgPty            TradeParty5                                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RptgPty"`
	RegnAgt            BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegnAgt"`
	RptgPrd            ReportingPeriod4                             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RptgPrd"`
	RegdCtrct          RegisteredContract8                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegdCtrct"`
	TxJrnl             []TransactionCertificate3                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TxJrnl,omitempty"`
	SpprtgDocJrnl      []SupportingDocument2                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SpprtgDocJrnl,omitempty"`
	AddtlSpprtgDocJrnl []SupportingDocument2                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AddtlSpprtgDocJrnl,omitempty"`
	RgltryRuleVldtn    []GenericValidationRuleIdentification1       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RgltryRuleVldtn,omitempty"`
	TtlCtrctTrnvrSum   ActiveCurrencyAndAmount                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TtlCtrctTrnvrSum"`
	SplmtryData        []SupplementaryData1                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SplmtryData,omitempty"`
}

type ContractRegistrationStatementV02 struct {
	GrpHdr      CurrencyControlHeader6           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 GrpHdr"`
	Stmt        []ContractRegistrationStatement2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Stmt"`
	SplmtryData []SupplementaryData1             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SplmtryData,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

// May be one of CRDT, DBIT
type CreditDebit3Code string

type CurrencyControlHeader6 struct {
	MsgId    Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MsgId"`
	CreDtTm  ISODateTime                                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CreDtTm"`
	NbOfItms Max15NumericText                             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 NbOfItms"`
	RcvgPty  PartyIdentification135                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RcvgPty"`
	RegnAgt  BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegnAgt"`
}

type DateAndPlaceOfBirth1 struct {
	BirthDt     ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 BirthDt"`
	PrvcOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PrvcOfBirth,omitempty"`
	CityOfBirth Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CityOfBirth"`
	CtryOfBirth CountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtryOfBirth"`
}

type DatePeriod3 struct {
	FrDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 FrDt"`
	ToDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ToDt,omitempty"`
}

// May be one of FITE, CALL
type DepositType1Code string

type Document struct {
	CtrctRegnStmt ContractRegistrationStatementV02 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrctRegnStmt"`
}

type DocumentAmendment1 struct {
	CrrctnId   float64   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CrrctnId"`
	OrgnlDocId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 OrgnlDocId,omitempty"`
}

type DocumentGeneralInformation3 struct {
	DocTp           ExternalDocumentType1Code  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DocTp"`
	DocNb           Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DocNb"`
	SndrRcvrSeqId   Max140Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SndrRcvrSeqId,omitempty"`
	IsseDt          ISODate                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IsseDt,omitempty"`
	URL             Max256Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 URL,omitempty"`
	LkFileHash      SignatureEnvelopeReference `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LkFileHash,omitempty"`
	AttchdBinryFile BinaryFile1                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AttchdBinryFile"`
}

type DocumentIdentification22 struct {
	Id       Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	DtOfIsse ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DtOfIsse,omitempty"`
}

type DocumentIdentification28 struct {
	Id       Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id,omitempty"`
	DtOfIsse ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DtOfIsse"`
}

type DocumentIdentification29 struct {
	Id       Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	DtOfIsse ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DtOfIsse"`
}

// Must match the pattern [0-9]
type Exact1NumericText string

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// Must match the pattern [0-9]{5}
type Exact5NumericText string

type ExchangeRate1 struct {
	UnitCcy  ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 UnitCcy,omitempty"`
	XchgRate float64                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XchgRate,omitempty"`
	RateTp   ExchangeRateType1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RateTp,omitempty"`
	CtrctId  Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrctId,omitempty"`
}

// May be one of SPOT, SALE, AGRD
type ExchangeRateType1Code string

// Must be at least 1 items long
type ExternalAccountIdentification1Code string

// Must be at least 1 items long
type ExternalCashAccountType1Code string

// Must be at least 1 items long
type ExternalClearingSystemIdentification1Code string

// Must be at least 1 items long
type ExternalContractBalanceType1Code string

// Must be at least 1 items long
type ExternalContractClosureReason1Code string

// Must be at least 1 items long
type ExternalDocumentType1Code string

// Must be at least 1 items long
type ExternalFinancialInstitutionIdentification1Code string

// Must be at least 1 items long
type ExternalOrganisationIdentification1Code string

// Must be at least 1 items long
type ExternalPersonIdentification1Code string

// Must be at least 1 items long
type ExternalProxyAccountType1Code string

// Must be at least 1 items long
type ExternalShipmentCondition1Code string

// Must be at least 1 items long
type ExternalValidationRuleIdentification1Code string

type FinancialIdentificationSchemeName1Choice struct {
	Cd    ExternalFinancialInstitutionIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type FinancialInstitutionIdentification18 struct {
	BICFI       BICFIDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 BICFI,omitempty"`
	ClrSysMmbId ClearingSystemMemberIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ClrSysMmbId,omitempty"`
	LEI         LEIIdentifier                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LEI,omitempty"`
	Nm          Max140Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Nm,omitempty"`
	PstlAdr     PostalAddress24                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PstlAdr,omitempty"`
	Othr        GenericFinancialIdentification1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Othr,omitempty"`
}

type FloatingInterestRate4 struct {
	RefRate    BenchmarkCurveName4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RefRate"`
	Term       InterestRateContractTerm1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Term"`
	BsisPtSprd float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 BsisPtSprd"`
}

type GenericAccountIdentification1 struct {
	Id      Max34Text                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	SchmeNm AccountSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SchmeNm,omitempty"`
	Issr    Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Issr,omitempty"`
}

type GenericFinancialIdentification1 struct {
	Id      Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	SchmeNm FinancialIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SchmeNm,omitempty"`
	Issr    Max35Text                                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Issr,omitempty"`
}

type GenericIdentification30 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	Issr    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Issr"`
	SchmeNm Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SchmeNm,omitempty"`
}

type GenericOrganisationIdentification1 struct {
	Id      Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	SchmeNm OrganisationIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SchmeNm,omitempty"`
	Issr    Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Issr,omitempty"`
}

type GenericPersonIdentification1 struct {
	Id      Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	SchmeNm PersonIdentificationSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SchmeNm,omitempty"`
	Issr    Max35Text                             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Issr,omitempty"`
}

type GenericValidationRuleIdentification1 struct {
	Id      Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
	Desc    Max350Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Desc,omitempty"`
	SchmeNm ValidationRuleSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SchmeNm,omitempty"`
	Issr    Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Issr,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}
type IBAN2007Identifier string

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type ISOTime time.Time

func (t *ISOTime) UnmarshalText(text []byte) error {
	return (*xsdTime)(t).UnmarshalText(text)
}
func (t ISOTime) MarshalText() ([]byte, error) {
	return xsdTime(t).MarshalText()
}

type InterestPaymentDateRange1 struct {
	IntrstSchdlId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IntrstSchdlId,omitempty"`
	XpctdDt       ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XpctdDt,omitempty"`
	DueDt         ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DueDt,omitempty"`
}

type InterestPaymentDateRange2 struct {
	IntrstSchdlId Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IntrstSchdlId,omitempty"`
	Amt           ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt"`
	DueDt         ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DueDt"`
	AddtlInf      Max1025Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AddtlInf,omitempty"`
}

type InterestPaymentSchedule1Choice struct {
	DtRg     InterestPaymentDateRange1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DtRg"`
	SubSchdl []InterestPaymentDateRange2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SubSchdl"`
}

type InterestRate2Choice struct {
	Fxd  float64               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Fxd"`
	Fltg FloatingInterestRate4 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Fltg"`
}

type InterestRateContractTerm1 struct {
	Unit RateBasis1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Unit"`
	Val  float64        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Val"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

type LegalOrganisation2 struct {
	Id           Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id,omitempty"`
	Nm           Max140Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Nm,omitempty"`
	EstblishmtDt ISODate    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 EstblishmtDt,omitempty"`
	RegnDt       ISODate    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegnDt,omitempty"`
}

type LoanContract2 struct {
	CtrctDocId  DocumentIdentification22       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrctDocId"`
	Buyr        []TradeParty5                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Buyr"`
	Sellr       []TradeParty5                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Sellr"`
	Amt         ActiveCurrencyAndAmount        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt"`
	MtrtyDt     ISODate                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MtrtyDt"`
	PrlngtnFlg  bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PrlngtnFlg"`
	StartDt     ISODate                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 StartDt"`
	SttlmCcy    ActiveCurrencyCode             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SttlmCcy"`
	SpclConds   SpecialCondition1              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SpclConds,omitempty"`
	DrtnCd      Exact1NumericText              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DrtnCd"`
	IntrstRate  InterestRate2Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IntrstRate"`
	Trch        []LoanContractTranche1         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Trch,omitempty"`
	PmtSchdl    PaymentSchedule1Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PmtSchdl,omitempty"`
	IntrstSchdl InterestPaymentSchedule1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IntrstSchdl"`
	IntraCpnyLn bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IntraCpnyLn"`
	Coll        ContractCollateral1            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Coll,omitempty"`
	SndctdLn    []SyndicatedLoan2              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SndctdLn,omitempty"`
	Attchmnt    []DocumentGeneralInformation3  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Attchmnt,omitempty"`
}

type LoanContractTranche1 struct {
	TrchNb      float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TrchNb"`
	XpctdDt     ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XpctdDt"`
	Amt         ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt"`
	DueDt       ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DueDt,omitempty"`
	DrtnCd      Exact1NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DrtnCd,omitempty"`
	LastTrchInd bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LastTrchInd,omitempty"`
}

type Max100KBinary []byte

func (t *Max100KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max100KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must be at least 1 items long
type Max1025Text string

// Must be at least 1 items long
type Max128Text string

// Must be at least 1 items long
type Max140Text string

// Must match the pattern [0-9]{1,15}
type Max15NumericText string

// Must be at least 1 items long
type Max16Text string

// Must be at least 1 items long
type Max2048Text string

// Must be at least 1 items long
type Max256Text string

// Must be at least 1 items long
type Max25Text string

// Must be at least 1 items long
type Max34Text string

// Must be at least 1 items long
type Max350Text string

// Must be at least 1 items long
type Max35Text string

// Must be at least 1 items long
type Max4Text string

// Must be at least 1 items long
type Max500Text string

// Must be at least 1 items long
type Max70Text string

// May be one of DOCT, MADM, MISS, MIST, MIKS
type NamePrefix2Code string

type OrganisationIdentification29 struct {
	AnyBIC AnyBICDec2014Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AnyBIC,omitempty"`
	LEI    LEIIdentifier                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LEI,omitempty"`
	Othr   []GenericOrganisationIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Othr,omitempty"`
}

type OrganisationIdentificationSchemeName1Choice struct {
	Cd    ExternalOrganisationIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type OtherContact1 struct {
	ChanlTp Max4Text   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ChanlTp"`
	Id      Max128Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id,omitempty"`
}

type Party38Choice struct {
	OrgId  OrganisationIdentification29 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 OrgId"`
	PrvtId PersonIdentification13       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PrvtId"`
}

type PartyIdentification135 struct {
	Nm        Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Nm,omitempty"`
	PstlAdr   PostalAddress24 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PstlAdr,omitempty"`
	Id        Party38Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id,omitempty"`
	CtryOfRes CountryCode     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtryOfRes,omitempty"`
	CtctDtls  Contact4        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtctDtls,omitempty"`
}

type PaymentDateRange1 struct {
	PmtSchdlId Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PmtSchdlId,omitempty"`
	XpctdDt    ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XpctdDt,omitempty"`
	DueDt      ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DueDt,omitempty"`
}

type PaymentDateRange2 struct {
	PmtSchdlId Max35Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PmtSchdlId,omitempty"`
	Amt        ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt"`
	XpctdDt    ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XpctdDt,omitempty"`
	DueDt      ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DueDt"`
}

type PaymentSchedule1Choice struct {
	DtRg     PaymentDateRange1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DtRg"`
	SubSchdl []PaymentDateRange2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SubSchdl"`
}

type PaymentScheduleType1Choice struct {
	Cd    PaymentScheduleType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

// May be one of CNTR, ESTM
type PaymentScheduleType1Code string

type PersonIdentification13 struct {
	DtAndPlcOfBirth DateAndPlaceOfBirth1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DtAndPlcOfBirth,omitempty"`
	Othr            []GenericPersonIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Othr,omitempty"`
}

type PersonIdentificationSchemeName1Choice struct {
	Cd    ExternalPersonIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

// Must match the pattern \+[0-9]{1,3}-[0-9()+\-]{1,30}
type PhoneNumber string

type PostalAddress24 struct {
	AdrTp       AddressType3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AdrTp,omitempty"`
	Dept        Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Dept,omitempty"`
	SubDept     Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SubDept,omitempty"`
	StrtNm      Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 StrtNm,omitempty"`
	BldgNb      Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 BldgNb,omitempty"`
	BldgNm      Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 BldgNm,omitempty"`
	Flr         Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Flr,omitempty"`
	PstBx       Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PstBx,omitempty"`
	Room        Max70Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Room,omitempty"`
	PstCd       Max16Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PstCd,omitempty"`
	TwnNm       Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TwnNm,omitempty"`
	TwnLctnNm   Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TwnLctnNm,omitempty"`
	DstrctNm    Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DstrctNm,omitempty"`
	CtrySubDvsn Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrySubDvsn,omitempty"`
	Ctry        CountryCode        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ctry,omitempty"`
	AdrLine     []Max70Text        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AdrLine,omitempty"`
}

// May be one of LETT, MAIL, PHON, FAXX, CELL
type PreferredContactMethod1Code string

type ProprietaryReference1 struct {
	Tp  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Tp"`
	Ref Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ref"`
}

type ProxyAccountIdentification1 struct {
	Tp ProxyAccountType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Tp,omitempty"`
	Id Max2048Text             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Id"`
}

type ProxyAccountType1Choice struct {
	Cd    ExternalProxyAccountType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

// May be one of ALLL, CHNG, MODF
type QueryType3Code string

// May be one of DAYS, MNTH, WEEK, YEAR
type RateBasis1Code string

type RegisteredContract8 struct {
	OrgnlCtrctRegnReq Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 OrgnlCtrctRegnReq,omitempty"`
	IssrFI            BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IssrFI"`
	Ctrct             UnderlyingContract2Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ctrct"`
	CtrctBal          []ContractBalance1                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrctBal,omitempty"`
	PmtSchdlTp        PaymentScheduleType1Choice                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PmtSchdlTp,omitempty"`
	RegdCtrctId       DocumentIdentification29                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegdCtrctId"`
	PrvsRegdCtrctId   DocumentIdentification22                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PrvsRegdCtrctId,omitempty"`
	RegdCtrctJrnl     []RegisteredContractJournal2                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegdCtrctJrnl,omitempty"`
	Amdmnt            []RegisteredContractAmendment1               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amdmnt,omitempty"`
	Submissn          RegisteredContractCommunication1             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Submissn"`
	Dlvry             RegisteredContractCommunication1             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Dlvry"`
	LnPrncplAmt       ActiveCurrencyAndAmount                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LnPrncplAmt,omitempty"`
	EstmtdDtInd       bool                                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 EstmtdDtInd"`
	IntrCpnyLn        bool                                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IntrCpnyLn"`
	AddtlInf          Max1025Text                                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AddtlInf,omitempty"`
}

type RegisteredContractAmendment1 struct {
	AmdmntDt  ISODate                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AmdmntDt"`
	Doc       DocumentIdentification28 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Doc"`
	StartDt   ISODate                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 StartDt,omitempty"`
	AmdmntRsn Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AmdmntRsn,omitempty"`
	AddtlInf  Max1025Text              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AddtlInf,omitempty"`
}

type RegisteredContractCommunication1 struct {
	Mtd CommunicationMethod4Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Mtd"`
	Dt  ISODate                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Dt"`
}

type RegisteredContractJournal2 struct {
	RegnAgt BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegnAgt"`
	UnqId   DocumentIdentification28                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 UnqId,omitempty"`
	ClsrDt  ISODate                                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ClsrDt"`
	ClsrRsn ContractClosureReason1Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ClsrRsn"`
}

type ReportingPeriod4 struct {
	FrToDt DatePeriod3    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 FrToDt"`
	FrToTm TimePeriod2    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 FrToTm"`
	Tp     QueryType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Tp"`
}

type ShipmentAttribute1 struct {
	Conds         ExternalShipmentCondition1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Conds,omitempty"`
	XpctdDt       ISODate                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XpctdDt,omitempty"`
	CtryOfCntrPty CountryCode                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtryOfCntrPty"`
}

type ShipmentDateRange1 struct {
	EarlstShipmntDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 EarlstShipmntDt,omitempty"`
	LatstShipmntDt  ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LatstShipmntDt,omitempty"`
}

type ShipmentDateRange2 struct {
	SubQtyVal       float64 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SubQtyVal"`
	EarlstShipmntDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 EarlstShipmntDt,omitempty"`
	LatstShipmntDt  ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LatstShipmntDt,omitempty"`
}

type ShipmentSchedule2Choice struct {
	ShipmntDtRg     ShipmentDateRange1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ShipmntDtRg"`
	ShipmntSubSchdl []ShipmentDateRange2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ShipmntSubSchdl"`
}

type SignatureEnvelopeReference struct {
	Item string `xml:",any"`
}

type SpecialCondition1 struct {
	IncmgAmt           ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IncmgAmt"`
	OutgngAmt          ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 OutgngAmt"`
	IncmgAmtToOthrAcct ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 IncmgAmtToOthrAcct,omitempty"`
	PmtFrOthrAcct      ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PmtFrOthrAcct,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type SupportingDocument2 struct {
	SpprtgDocId Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SpprtgDocId"`
	OrgnlReqId  Max35Text                                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 OrgnlReqId,omitempty"`
	Cert        DocumentIdentification28                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cert"`
	AcctOwnr    PartyIdentification135                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AcctOwnr"`
	AcctSvcr    BranchAndFinancialInstitutionIdentification6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AcctSvcr"`
	Amdmnt      DocumentAmendment1                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amdmnt,omitempty"`
	CtrctRef    ContractRegistrationReference1Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrctRef"`
	Ntry        []SupportingDocumentEntry1                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ntry"`
	SplmtryData []SupplementaryData1                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SplmtryData,omitempty"`
}

type SupportingDocumentEntry1 struct {
	NtryId                      Max35Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 NtryId"`
	OrgnlDoc                    DocumentIdentification22      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 OrgnlDoc"`
	DocTp                       Exact4AlphaNumericText        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 DocTp"`
	TtlAmt                      ActiveCurrencyAndAmount       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TtlAmt,omitempty"`
	TtlAmtAftrShipmnt           ActiveCurrencyAndAmount       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TtlAmtAftrShipmnt,omitempty"`
	TtlAmtInCtrctCcy            ActiveCurrencyAndAmount       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TtlAmtInCtrctCcy,omitempty"`
	TtlAmtAftrShipmntInCtrctCcy ActiveCurrencyAndAmount       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TtlAmtAftrShipmntInCtrctCcy,omitempty"`
	ShipmntAttrbts              ShipmentAttribute1            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ShipmntAttrbts"`
	AddtlInf                    Max500Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AddtlInf,omitempty"`
	Attchmnt                    []DocumentGeneralInformation3 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Attchmnt,omitempty"`
}

type SyndicatedLoan2 struct {
	Brrwr       TradeParty5             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Brrwr"`
	Lndr        TradeParty5             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Lndr,omitempty"`
	Amt         ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt,omitempty"`
	Shr         float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Shr,omitempty"`
	XchgRateInf ExchangeRate1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XchgRateInf,omitempty"`
}

// May be one of NONE, MASA, MISA, SISA, IISA, CUYP, PRYP, ASTR, EMPY, EMCY, EPRY, ECYE, NFPI, NFQP, DECP, IRAC, IRAR, KEOG, PFSP, 401K, SIRA, 403B, 457X, RIRA, RIAN, RCRF, RCIP, EIFP, EIOP
type TaxExemptReason1Code string

type TaxExemptionReasonFormat1Choice struct {
	Ustrd Max140Text           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ustrd"`
	Strd  TaxExemptReason1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Strd"`
}

type TaxParty4 struct {
	TaxId       Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TaxId,omitempty"`
	TaxTp       Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TaxTp,omitempty"`
	RegnId      Max35Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RegnId,omitempty"`
	TaxXmptnRsn []TaxExemptionReasonFormat1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TaxXmptnRsn,omitempty"`
}

type TimePeriod2 struct {
	FrTm ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 FrTm"`
	ToTm ISOTime `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ToTm,omitempty"`
}

type TradeContract2 struct {
	CtrctDocId   DocumentIdentification22      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrctDocId,omitempty"`
	Amt          ActiveCurrencyAndAmount       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt"`
	Buyr         []TradeParty5                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Buyr"`
	Sellr        []TradeParty5                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Sellr"`
	MtrtyDt      ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 MtrtyDt"`
	PrlngtnFlg   bool                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PrlngtnFlg"`
	StartDt      ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 StartDt"`
	SttlmCcy     ActiveCurrencyCode            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SttlmCcy"`
	XchgRateInf  ExchangeRate1                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XchgRateInf,omitempty"`
	PmtSchdl     InterestPaymentDateRange1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PmtSchdl,omitempty"`
	ShipmntSchdl ShipmentSchedule2Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 ShipmntSchdl,omitempty"`
	Attchmnt     []DocumentGeneralInformation3 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Attchmnt,omitempty"`
}

type TradeParty5 struct {
	PtyId  PartyIdentification135 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 PtyId"`
	LglOrg LegalOrganisation2     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LglOrg,omitempty"`
	TaxPty []TaxParty4            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TaxPty,omitempty"`
}

type TransactionCertificate2 struct {
	RfrdDoc   CertificateReference1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 RfrdDoc"`
	TxDt      ISODate                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TxDt"`
	TxTp      Exact1NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TxTp"`
	LclInstrm Exact5NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 LclInstrm"`
	Amt       ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amt"`
}

type TransactionCertificate3 struct {
	TxId             Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TxId"`
	Cert             DocumentIdentification28        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cert"`
	Acct             CashAccount38                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Acct,omitempty"`
	BkAcctDmcltnCtry CountryCode                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 BkAcctDmcltnCtry,omitempty"`
	Amdmnt           DocumentAmendment1              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Amdmnt,omitempty"`
	CertRcrd         []TransactionCertificateRecord1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CertRcrd"`
	SplmtryData      []SupplementaryData1            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 SplmtryData,omitempty"`
}

type TransactionCertificateContract1 struct {
	CtrctRef           ContractRegistrationReference1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CtrctRef,omitempty"`
	TxAmtInCtrctCcy    ActiveCurrencyAndAmount              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 TxAmtInCtrctCcy,omitempty"`
	XpctdShipmntDt     ISODate                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XpctdShipmntDt,omitempty"`
	XpctdAdvncPmtRtrDt ISODate                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 XpctdAdvncPmtRtrDt,omitempty"`
	AddtlInf           Max1025Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 AddtlInf,omitempty"`
}

type TransactionCertificateRecord1 struct {
	CertRcrdId Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 CertRcrdId"`
	Tx         TransactionCertificate2         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Tx"`
	Ctrct      TransactionCertificateContract1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ctrct,omitempty"`
	Attchmnt   []DocumentGeneralInformation3   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Attchmnt,omitempty"`
}

type UnderlyingContract2Choice struct {
	Ln   LoanContract2  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Ln"`
	Trad TradeContract2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Trad"`
}

type ValidationRuleSchemeName1Choice struct {
	Cd    ExternalValidationRuleIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Cd"`
	Prtry Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.022.001.02 Prtry"`
}

type xsdBase64Binary []byte

func (b *xsdBase64Binary) UnmarshalText(text []byte) (err error) {
	*b, err = base64.StdEncoding.DecodeString(string(text))
	return
}
func (b xsdBase64Binary) MarshalText() ([]byte, error) {
	var buf bytes.Buffer
	enc := base64.NewEncoder(base64.StdEncoding, &buf)
	enc.Write([]byte(b))
	enc.Close()
	return buf.Bytes(), nil
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}

type xsdTime time.Time

func (t *xsdTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
